namespace ISmart;

public enum TOKEN_ERROR
{
	SUCCESS,
	INVALID_IP_FORMAT,
	MSG_BUF_SIZE_TOO_SMALL,
	SOCKET_NOT_OPEN,
	TLS_SRV_REFUSE_CON,
	TLS_COM_FAIL,
	TOKEN_OPEN_FAIL,
	TOKEN_INTERNAL_ERR,
	TOKEN_ID_MISMATCH,
	TOKEN_NOT_PRESENT,
	INVALID_VERSION,
	INVALID_MSG_FORMAT,
	INVALID_USER_ID,
	TOKEN_SIGN_ERR,
	TOKEN_KEY_NOT_FOUND,
	TOKEN_DECRYPT_FAILED,
	TOKEN_BLOCK_WRONG_SIZE,
	TOKEN_GEN_DATA_BLOCK_FAIL,
	TOKEN_EXPONENT_TOO_LARGE,
	TOKEN_TOO_MANY_DATABLOCKS,
	TOKEN_WRONG_DATABLOCK_TYPE
}
