using System;

namespace AuthenticodeExaminer.Interop;

[Flags]
internal enum CryptQueryContentFlagType : uint
{
	CERT_QUERY_CONTENT_FLAG_CERT = 2u,
	CERT_QUERY_CONTENT_FLAG_CTL = 4u,
	CERT_QUERY_CONTENT_FLAG_CRL = 8u,
	CERT_QUERY_CONTENT_FLAG_SERIALIZED_STORE = 0x10u,
	CERT_QUERY_CONTENT_FLAG_SERIALIZED_CERT = 0x20u,
	CERT_QUERY_CONTENT_FLAG_SERIALIZED_CTL = 0x40u,
	CERT_QUERY_CONTENT_FLAG_SERIALIZED_CRL = 0x80u,
	CERT_QUERY_CONTENT_FLAG_PKCS7_SIGNED = 0x100u,
	CERT_QUERY_CONTENT_FLAG_PKCS7_UNSIGNED = 0x200u,
	CERT_QUERY_CONTENT_FLAG_PKCS7_SIGNED_EMBED = 0x400u,
	CERT_QUERY_CONTENT_FLAG_PKCS10 = 0x800u,
	CERT_QUERY_CONTENT_FLAG_PFX = 0x1000u,
	CERT_QUERY_CONTENT_FLAG_CERT_PAIR = 0x2000u,
	CERT_QUERY_CONTENT_FLAG_PFX_AND_LOAD = 0x4000u,
	CERT_QUERY_CONTENT_FLAG_ALL = 0x3FFEu,
	CERT_QUERY_CONTENT_FLAG_ALL_ISSUER_CERT = 0x332u
}
