using System;

namespace AuthenticodeExaminer.Interop;

[Flags]
internal enum WinTrustProviderFlags : uint
{
	NONE = 0u,
	WTD_USE_IE4_TRUST_FLAG = 1u,
	WTD_NO_IE4_CHAIN_FLAG = 2u,
	WTD_NO_POLICY_USAGE_FLAG = 4u,
	WTD_REVOCATION_CHECK_NONE = 0x10u,
	WTD_REVOCATION_CHECK_END_CERT = 0x20u,
	WTD_REVOCATION_CHECK_CHAIN = 0x40u,
	WTD_REVOCATION_CHECK_CHAIN_EXCLUDE_ROOT = 0x80u,
	WTD_SAFER_FLAG = 0x100u,
	WTD_HASH_ONLY_FLAG = 0x200u,
	WTD_USE_DEFAULT_OSVER_CHECK = 0x400u,
	WTD_LIFETIME_SIGNING_FLAG = 0x800u,
	WTD_CACHE_ONLY_URL_RETRIEVAL = 0x1000u,
	WTD_DISABLE_MD2_MD4 = 0x2000u,
	WTD_MOTW = 0x4000u
}
